-- File này được sinh tự động bởi scripts/generate-seed.ts - đừng sửa tay.
-- Chạy lại: npm run seed:gen

begin;

-- Xoá dữ liệu danh mục cũ (không đụng tới bảng của người dùng)
delete from tlrm.dish_ingredients;
delete from tlrm.dishes;
delete from tlrm.ingredients;

insert into tlrm.ingredients (id, name, emoji, category, staple, aliases) values
  ('thit-ba-chi', 'Thịt ba chỉ', '🥓', 'thit', false, array['thịt heo', 'thịt lợn', 'ba rọi']),
  ('thit-nac-vai', 'Thịt nạc vai', '🥩', 'thit', false, array['nạc vai', 'thịt nạc']),
  ('thit-bam', 'Thịt băm', '🍖', 'thit', false, array['thịt xay', 'thịt heo bằm']),
  ('suon-non', 'Sườn non', '🍖', 'thit', false, array['sườn', 'sườn heo']),
  ('thit-bo', 'Thịt bò', '🥩', 'thit', false, array['bò', 'bắp bò']),
  ('uc-ga', 'Ức gà', '🍗', 'thit', false, array['gà', 'thịt gà']),
  ('dui-ga', 'Đùi gà', '🍗', 'thit', false, array['đùi gà', 'cánh gà', 'gà góc tư']),
  ('tom', 'Tôm', '🦐', 'hai-san', false, array['tôm sú', 'tôm thẻ']),
  ('ca-basa', 'Cá basa', '🐟', 'hai-san', false, array['cá tra', 'cá phi lê', 'cá diêu hồng']),
  ('ca-thu', 'Cá thu', '🐟', 'hai-san', false, array['cá ngừ']),
  ('muc', 'Mực', '🦑', 'hai-san', false, array['mực ống', 'mực lá']),
  ('ngheu', 'Nghêu', '🐚', 'hai-san', false, array['ngao', 'hến']),
  ('rau-muong', 'Rau muống', '🥬', 'rau', false, array['muống']),
  ('cai-ngot', 'Cải ngọt', '🥬', 'rau', false, array['cải xanh', 'cải bẹ']),
  ('cai-thao', 'Cải thảo', '🥬', 'rau', false, array['cải bắc thảo']),
  ('bap-cai', 'Bắp cải', '🥬', 'rau', false, array['cải bắp']),
  ('mong-toi', 'Mồng tơi', '🌿', 'rau', false, array['rau mồng tơi']),
  ('rau-den', 'Rau dền', '🌿', 'rau', false, array['dền']),
  ('gia-do', 'Giá đỗ', '🌱', 'rau', false, array['giá']),
  ('nam-rom', 'Nấm rơm', '🍄', 'rau', false, array['nấm', 'nấm bào ngư', 'nấm kim châm']),
  ('hanh-la', 'Hành lá', '🌿', 'rau', true, '{}'),
  ('rau-thom', 'Rau thơm', '🌿', 'rau', true, '{}'),
  ('ca-chua', 'Cà chua', '🍅', 'cu-qua', false, array['cà chua bi']),
  ('dua-chuot', 'Dưa chuột', '🥒', 'cu-qua', false, array['dưa leo']),
  ('bi-xanh', 'Bí xanh', '🥒', 'cu-qua', false, array['bí đao']),
  ('bi-do', 'Bí đỏ', '🎃', 'cu-qua', false, array['bí ngô']),
  ('ca-rot', 'Cà rốt', '🥕', 'cu-qua', false, '{}'),
  ('khoai-tay', 'Khoai tây', '🥔', 'cu-qua', false, array['củ khoai tây']),
  ('su-su', 'Su su', '🥒', 'cu-qua', false, '{}'),
  ('dau-que', 'Đậu que', '🫛', 'cu-qua', false, array['đậu cove', 'đậu đũa']),
  ('hanh-tay', 'Hành tây', '🧅', 'cu-qua', false, array['củ hành tây']),
  ('khom', 'Thơm (dứa)', '🍍', 'cu-qua', false, array['dứa', 'thơm']),
  ('me', 'Me', '🫘', 'cu-qua', false, '{}'),
  ('chanh', 'Chanh', '🍋', 'cu-qua', true, '{}'),
  ('toi', 'Tỏi', '🧄', 'cu-qua', true, '{}'),
  ('hanh-tim', 'Hành tím', '🧅', 'cu-qua', true, '{}'),
  ('ot', 'Ớt', '🌶️', 'cu-qua', true, '{}'),
  ('gung', 'Gừng', '🫚', 'cu-qua', true, '{}'),
  ('trung-ga', 'Trứng gà', '🥚', 'trung-sua', false, array['trứng', 'trứng vịt', 'trứng cút']),
  ('dau-hu', 'Đậu hũ', '🧈', 'trung-sua', false, array['đậu phụ', 'tàu hũ', 'đậu hủ']),
  ('sua-tuoi', 'Sữa tươi', '🥛', 'trung-sua', false, '{}'),
  ('gao', 'Gạo', '🍚', 'kho', true, '{}'),
  ('bun', 'Bún', '🍜', 'kho', false, '{}'),
  ('mien', 'Miến', '🍜', 'kho', false, '{}'),
  ('banh-pho', 'Bánh phở', '🍜', 'kho', false, array['phở', 'hủ tiếu']),
  ('lac', 'Lạc (đậu phộng)', '🥜', 'kho', false, array['đậu phộng']),
  ('banh-mi', 'Bánh mì', '🥖', 'kho', false, '{}'),
  ('mi-goi', 'Mì gói', '🍜', 'kho', false, array['mì tôm', 'mì ăn liền']),
  ('yen-mach', 'Yến mạch', '🥣', 'kho', false, '{}'),
  ('ngu-coc', 'Ngũ cốc', '🫙', 'kho', false, '{}'),
  ('nuoc-mam', 'Nước mắm', '🧂', 'gia-vi', true, '{}'),
  ('dau-an', 'Dầu ăn', '🫗', 'gia-vi', true, '{}'),
  ('muoi', 'Muối', '🧂', 'gia-vi', true, '{}'),
  ('duong', 'Đường', '🍬', 'gia-vi', true, '{}'),
  ('tieu', 'Tiêu', '🧂', 'gia-vi', true, '{}'),
  ('hat-nem', 'Hạt nêm', '🧂', 'gia-vi', true, '{}'),
  ('nuoc-tuong', 'Nước tương', '🍶', 'gia-vi', true, '{}'),
  ('dau-hao', 'Dầu hào', '🍶', 'gia-vi', true, '{}');

insert into tlrm.dishes (id, slug, name, emoji, summary, role, slots, minutes, servings, difficulty, tags, kcal, protein, carb, fat, steps, tip) values
  ('thit-kho-trung', 'thit-kho-trung', 'Thịt kho trứng', '🍳', 'Món kho quen thuộc, làm một nồi ăn được hai bữa.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 40, 4, 1, array['trẻ em thích', 'nấu 1 lần ăn 2 bữa'], 430, 26, 6, 33, array['Thịt ba chỉ cắt miếng vuông 3cm, ướp với 1 thìa nước mắm, 1 thìa đường, tiêu, hành tím băm — để 15 phút.', 'Luộc trứng 8 phút, bóc vỏ.', 'Thắng 1 thìa đường tới màu cánh gián, cho thịt vào đảo săn.', 'Đổ nước dừa hoặc nước lọc xâm xấp mặt thịt, kho lửa nhỏ 25 phút.', 'Cho trứng vào kho thêm 10 phút, nêm lại cho vừa miệng.'], 'Kho tối hôm trước, sáng hâm lại là có bữa trưa mang đi làm.'),
  ('ga-kho-gung', 'ga-kho-gung', 'Gà kho gừng', '🍗', 'Đậm đà, thơm gừng, hợp bữa tối trời mát.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 30, 4, 1, array['dễ nấu', 'ấm bụng'], 380, 32, 8, 24, array['Đùi gà chặt miếng vừa ăn, ướp nước mắm, hạt nêm, tiêu 15 phút.', 'Phi thơm gừng thái sợi với chút dầu.', 'Cho gà vào đảo săn, thêm 1 thìa đường và nước xâm xấp.', 'Kho lửa vừa 20 phút tới khi nước sánh lại, rắc hành lá.'], null),
  ('ca-kho-to', 'ca-kho-to', 'Cá kho tộ', '🐟', 'Cá kho nước màu, ăn với cơm nóng là hết nồi.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 35, 4, 2, array['đậm đà'], 320, 28, 7, 19, array['Cá cắt khúc, xát muối và gừng cho sạch nhớt, để ráo.', 'Ướp cá với nước mắm, đường, tiêu, hành tím 20 phút.', 'Thắng nước màu, xếp cá vào nồi, thêm nước xâm xấp.', 'Kho lửa nhỏ 25 phút, rưới nước kho lên mặt cá vài lần.'], 'Thêm vài lát thịt ba chỉ kho cùng cho cá béo và không bị khô.'),
  ('tom-rang-thit', 'tom-rang-thit', 'Tôm rang thịt', '🦐', 'Món mặn nhanh, trẻ con rất chịu ăn cơm.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 20, 4, 1, array['nhanh', 'trẻ em thích'], 290, 30, 6, 15, array['Tôm bóc vỏ, bỏ chỉ đen, ướp chút hạt nêm và tiêu.', 'Phi thơm hành tím, cho thịt băm vào xào tơi.', 'Cho tôm vào rang cùng, nêm nước mắm và chút đường.', 'Rang tới khi săn và hơi cháy cạnh, rắc hành lá.'], null),
  ('trung-chien-thit-bam', 'trung-chien-thit-bam', 'Trứng chiên thịt băm', '🍳', 'Cứu cánh 10 phút cho hôm về muộn.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 10, 4, 1, array['10 phút', 'trẻ em thích', 'dễ nấu'], 260, 20, 3, 19, array['Đánh tan trứng với chút hạt nêm và tiêu.', 'Xào thịt băm với hành tím cho chín tới, để nguội bớt.', 'Trộn thịt và hành lá vào trứng, chiên lửa vừa hai mặt.'], null),
  ('thit-bo-xao-hanh-tay', 'thit-bo-xao-hanh-tay', 'Bò xào hành tây', '🥩', '15 phút, nhiều đạm, hợp bữa tối nhẹ.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 15, 4, 2, array['nhanh', 'nhiều đạm'], 310, 29, 9, 18, array['Bò thái mỏng ngang thớ, ướp dầu hào, tỏi băm, tiêu 10 phút.', 'Chảo thật nóng, xào bò 1–2 phút rồi trút ra đĩa.', 'Xào hành tây tới khi trong, trả bò vào đảo nhanh rồi tắt bếp.'], 'Xào bò riêng rồi trộn lại — bò sẽ mềm, không ra nước.'),
  ('suon-xao-chua-ngot', 'suon-xao-chua-ngot', 'Sườn xào chua ngọt', '🍖', 'Món tủ của trẻ con, cả nhà đều ăn được.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 40, 4, 2, array['trẻ em thích'], 410, 27, 18, 26, array['Sườn chặt miếng, chần qua nước sôi cho sạch rồi để ráo.', 'Chiên sườn vàng các mặt, trút ra.', 'Phi tỏi, cho cà chua vào xào nhuyễn, nêm đường, giấm/chanh, nước mắm.', 'Trả sườn vào, rim 10 phút cho ngấm và sốt sánh.'], null),
  ('dau-hu-sot-ca', 'dau-hu-sot-ca-chua', 'Đậu hũ sốt cà chua', '🍅', 'Món chay nhanh, rẻ, nhẹ bụng bữa tối.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 20, 4, 1, array['dễ nấu', 'ít dầu mỡ', 'chay được'], 210, 14, 12, 12, array['Đậu hũ cắt miếng, chiên sơ cho vàng mặt.', 'Xào cà chua với hành tím tới khi nhuyễn, thêm chút nước.', 'Cho đậu hũ vào rim 5 phút, nêm nước mắm, rắc hành lá.'], null),
  ('ga-chien-nuoc-mam', 'ga-chien-nuoc-mam', 'Gà chiên nước mắm', '🍗', 'Giòn mặn ngọt, làm nhanh mà trông như đãi khách.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 30, 4, 2, array['trẻ em thích'], 400, 31, 10, 26, array['Gà chặt miếng, ướp muối tiêu 15 phút rồi chiên vàng.', 'Nấu sốt: 2 thìa nước mắm + 2 thìa đường + tỏi băm, đun tới khi sánh.', 'Cho gà vào đảo đều cho áo hết sốt.'], null),
  ('muc-xao-can', 'muc-xao-can', 'Mực xào cần tỏi', '🦑', 'Nhanh, ngọt tự nhiên, ít dầu mỡ.', 'man', array['trua', 'toi']::tlrm.meal_slot[], 20, 4, 2, array['nhanh', 'ít dầu mỡ'], 240, 26, 9, 11, array['Mực làm sạch, khía vảy rồng, chần 30 giây rồi vớt ra.', 'Phi tỏi, xào hành tây và cà rốt.', 'Cho mực vào xào lửa lớn 2 phút, nêm dầu hào và tiêu.'], null),
  ('banh-mi-trung-op-la', 'banh-mi-trung-op-la', 'Bánh mì trứng ốp la', '🍳', 'Vài phút có bữa sáng nóng, cả nhà ăn được.', 'man', array['sang']::tlrm.meal_slot[], 8, 2, 1, array['10 phút', 'trẻ em thích'], 340, 15, 34, 16, array['Đun chảo với chút dầu, đập trứng vào chiên lửa vừa 2 phút.', 'Rắc chút muối tiêu, tắt bếp khi lòng đỏ còn hơi lỏng.', 'Nướng nhanh bánh mì cho giòn rồi kẹp trứng, thêm dưa chuột.'], 'Tối trước nướng sẵn bánh mì, sáng chỉ tốn 3 phút.'),
  ('mi-goi-trung', 'mi-goi-trung', 'Mì gói thả trứng', '🍜', 'Cứu cánh hôm dậy muộn, thêm rau cho đỡ khô.', 'man', array['sang']::tlrm.meal_slot[], 7, 1, 1, array['10 phút', 'dễ nấu'], 420, 14, 52, 17, array['Đun sôi 500ml nước, thả mì và gói gia vị.', 'Đập trứng vào, để lửa nhỏ 2 phút cho trứng se lại.', 'Cho rau vào, sôi lại là tắt bếp.'], null),
  ('chao-thit-bam', 'chao-thit-bam', 'Cháo thịt băm', '🥣', 'Nấu nồi cháo sáng, trẻ nhỏ ăn dễ.', 'man', array['sang']::tlrm.meal_slot[], 30, 4, 1, array['trẻ em thích', 'nấu 1 lần ăn 2 bữa'], 250, 13, 34, 7, array['Vo gạo, nấu với nhiều nước khoảng 20 phút cho nhừ.', 'Xào thịt băm với hành tím cho săn rồi trút vào nồi cháo.', 'Nêm nước mắm, rắc hành lá và tiêu.'], 'Dùng nồi cơm điện chế độ cháo, cắm từ tối hôm trước.'),
  ('com-rang-trung', 'com-rang-trung', 'Cơm rang trứng', '🍚', 'Tận dụng cơm nguội tối qua, 10 phút là xong.', 'man', array['sang']::tlrm.meal_slot[], 10, 2, 1, array['10 phút', 'đỡ phí đồ ăn'], 380, 12, 48, 14, array['Đánh tan trứng, tráng mỏng rồi thái sợi.', 'Phi hành, cho cơm nguội vào rang tơi trên lửa lớn.', 'Trả trứng vào, nêm nước tương, rắc hành lá.'], null),
  ('mien-xao-trung', 'mien-xao-trung', 'Miến xào trứng', '🍜', 'Nhẹ bụng, ít dầu mỡ, làm nhanh.', 'man', array['sang']::tlrm.meal_slot[], 15, 2, 1, array['ít dầu mỡ', 'dễ nấu'], 330, 12, 45, 11, array['Ngâm miến nước ấm 5 phút rồi vớt ra để ráo.', 'Chiên trứng, thái sợi để riêng.', 'Xào cà rốt và giá, cho miến vào đảo nhanh, nêm nước tương rồi trộn trứng.'], null),
  ('yen-mach-sua', 'yen-mach-sua', 'Yến mạch sữa', '🥛', 'Không cần bếp, hợp hôm phải ra khỏi nhà sớm.', 'man', array['sang']::tlrm.meal_slot[], 5, 1, 1, array['10 phút', 'ít dầu mỡ'], 300, 12, 42, 9, array['Cho yến mạch vào bát, đổ sữa nóng ngập mặt.', 'Đậy nắp 3 phút cho nở mềm.', 'Thêm lạc rang giã nhỏ hoặc hoa quả nếu có.'], 'Ngâm sẵn từ tối, sáng lấy trong tủ lạnh ra ăn luôn.'),
  ('ngu-coc-sua', 'ngu-coc-sua', 'Ngũ cốc sữa', '🫙', 'Không cần bếp, hợp hôm phải ra khỏi nhà sớm.', 'man', array['sang']::tlrm.meal_slot[], 5, 1, 1, array['10 phút', 'ít dầu mỡ'], 300, 12, 42, 9, array['Cho yến mạch vào bát, đổ sữa nóng ngập mặt.', 'Đậy nắp 3 phút cho nở mềm.', 'Thêm lạc rang giã nhỏ hoặc hoa quả nếu có.'], 'Ngâm sẵn từ tối, sáng lấy trong tủ lạnh ra ăn luôn.'),
  ('canh-chua-ca', 'canh-chua-ca', 'Canh chua cá', '🍲', 'Chua thanh, đưa cơm, hợp bữa tối nóng nực.', 'canh', array['trua', 'toi']::tlrm.meal_slot[], 30, 4, 2, array['giải nhiệt'], 160, 17, 10, 6, array['Nấu nước me (hoặc me chua) lấy nước cốt.', 'Đun sôi nước, cho cà chua và thơm vào nấu 5 phút.', 'Cho cá vào nấu 7 phút, hớt bọt, nêm nước mắm và đường.', 'Cho giá đỗ và rau thơm vào rồi tắt bếp ngay.'], null),
  ('canh-rau-ngot-thit-bam', 'canh-rau-thit-bam', 'Canh rau nấu thịt băm', '🥬', '10 phút có canh, dùng được với hầu hết loại rau.', 'canh', array['trua', 'toi']::tlrm.meal_slot[], 10, 4, 1, array['10 phút', 'dễ nấu'], 110, 11, 5, 5, array['Phi hành tím, xào thịt băm cho săn.', 'Đổ nước, đun sôi, hớt bọt.', 'Cho rau vào, sôi lại là tắt bếp, nêm nước mắm.'], null),
  ('canh-bi-xanh-tom', 'canh-bi-xanh-tom', 'Canh bí xanh nấu tôm', '🍲', 'Ngọt nước, mát, dễ ăn cho cả nhà.', 'canh', array['trua', 'toi']::tlrm.meal_slot[], 20, 4, 1, array['dễ nấu', 'ít dầu mỡ'], 95, 12, 7, 2, array['Tôm bóc vỏ, băm nhỏ, ướp chút hạt nêm.', 'Xào tôm cho thơm rồi đổ nước đun sôi.', 'Cho bí xanh thái miếng vào nấu 8 phút, nêm vừa ăn.'], null),
  ('canh-ngheu-bau', 'canh-ngheu', 'Canh nghêu nấu chua', '🐚', 'Nước ngọt tự nhiên, nấu chưa tới 20 phút.', 'canh', array['trua', 'toi']::tlrm.meal_slot[], 20, 4, 2, array['giải nhiệt'], 100, 13, 8, 2, array['Ngâm nghêu với nước muối loãng và ớt cho nhả cát.', 'Luộc nghêu tới khi mở miệng, lọc lấy nước trong.', 'Xào cà chua, đổ nước nghêu vào đun sôi, thả nghêu và rau thơm.'], null),
  ('canh-trung-ca-chua', 'canh-trung-ca-chua', 'Canh trứng cà chua', '🥚', 'Rẻ, nhanh, hầu như lúc nào cũng nấu được.', 'canh', array['trua', 'toi']::tlrm.meal_slot[], 10, 4, 1, array['10 phút', 'dễ nấu'], 105, 8, 6, 6, array['Xào cà chua với hành tím cho ra màu.', 'Đổ nước đun sôi, nêm vừa ăn.', 'Rót trứng đã đánh tan thành dòng mỏng, khuấy nhẹ rồi tắt bếp.'], null),
  ('canh-suon-bi-do', 'canh-suon-bi-do', 'Canh sườn bí đỏ', '🎃', 'Ngọt nước, nhiều vitamin A, trẻ con dễ ăn.', 'canh', array['trua', 'toi']::tlrm.meal_slot[], 45, 4, 1, array['cuối tuần', 'trẻ em thích'], 180, 15, 14, 8, array['Sườn chần qua nước sôi, rửa sạch.', 'Hầm sườn 25 phút với chút muối, hớt bọt.', 'Cho bí đỏ vào nấu thêm 12 phút cho mềm, nêm vừa ăn.'], null),
  ('rau-muong-xao-toi', 'rau-muong-xao-toi', 'Rau muống xào tỏi', '🥬', 'Món rau kinh điển, 7 phút là xong.', 'rau', array['trua', 'toi']::tlrm.meal_slot[], 7, 4, 1, array['10 phút', 'dễ nấu'], 90, 3, 8, 6, array['Rau nhặt, rửa sạch, để ráo.', 'Phi thơm tỏi với dầu, cho rau vào xào lửa lớn.', 'Nêm hạt nêm, đảo nhanh 3 phút rồi tắt bếp.'], null),
  ('bap-cai-luoc', 'bap-cai-luoc', 'Bắp cải luộc chấm trứng', '🥬', 'Không dầu mỡ, nước luộc dùng làm canh luôn.', 'rau', array['trua', 'toi']::tlrm.meal_slot[], 12, 4, 1, array['ít dầu mỡ', 'dễ nấu'], 60, 3, 10, 1, array['Bắp cải thái miếng to, rửa sạch.', 'Luộc trong nước sôi có chút muối 5–7 phút.', 'Pha nước mắm trứng hoặc nước mắm chanh ớt để chấm.'], 'Giữ lại nước luộc, vắt chanh vào là có bát canh thanh mát.'),
  ('su-su-xao-ca-rot', 'su-su-xao-ca-rot', 'Su su xào cà rốt', '🥕', 'Ngọt nhẹ, nhiều màu, hợp đổi món giữa tuần.', 'rau', array['trua', 'toi']::tlrm.meal_slot[], 12, 4, 1, array['dễ nấu'], 95, 3, 12, 5, array['Su su và cà rốt gọt vỏ, thái miếng vừa.', 'Phi tỏi, xào cà rốt trước 2 phút rồi cho su su vào.', 'Thêm chút nước, đậy vung 4 phút, nêm vừa ăn.'], null),
  ('dau-que-xao-thit', 'dau-que-xao-thit', 'Đậu que xào thịt bằm', '🫛', 'Vừa rau vừa đạm, một chảo là đủ.', 'rau', array['trua', 'toi']::tlrm.meal_slot[], 15, 4, 1, array['dễ nấu', 'một chảo'], 150, 12, 9, 8, array['Đậu que tước xơ, cắt khúc, chần 1 phút.', 'Xào thịt băm với tỏi cho săn.', 'Cho đậu que vào xào 4 phút, nêm nước mắm và tiêu.'], null),
  ('cai-thao-xao-nam', 'cai-thao-xao-nam', 'Cải thảo xào nấm', '🍄', 'Món chay nhẹ, ngọt nước, ăn tối không nặng bụng.', 'rau', array['toi']::tlrm.meal_slot[], 12, 4, 1, array['ít dầu mỡ', 'chay được'], 85, 4, 9, 4, array['Cải thảo thái miếng, nấm rửa sạch bổ đôi.', 'Phi tỏi, xào nấm 2 phút cho thơm.', 'Cho cải thảo vào xào lửa lớn 4 phút, nêm dầu hào.'], null);

insert into tlrm.dish_ingredients (dish_id, ingredient_id, required, position) values
  ('thit-kho-trung', 'thit-ba-chi', true, 0),
  ('thit-kho-trung', 'trung-ga', true, 1),
  ('thit-kho-trung', 'hanh-tim', false, 0),
  ('thit-kho-trung', 'toi', false, 1),
  ('ga-kho-gung', 'dui-ga', true, 0),
  ('ga-kho-gung', 'gung', true, 1),
  ('ga-kho-gung', 'hanh-la', false, 0),
  ('ga-kho-gung', 'ot', false, 1),
  ('ca-kho-to', 'ca-basa', true, 0),
  ('ca-kho-to', 'ot', false, 0),
  ('ca-kho-to', 'hanh-tim', false, 1),
  ('ca-kho-to', 'thit-ba-chi', false, 2),
  ('tom-rang-thit', 'tom', true, 0),
  ('tom-rang-thit', 'thit-bam', true, 1),
  ('tom-rang-thit', 'hanh-la', false, 0),
  ('tom-rang-thit', 'hanh-tim', false, 1),
  ('trung-chien-thit-bam', 'trung-ga', true, 0),
  ('trung-chien-thit-bam', 'thit-bam', true, 1),
  ('trung-chien-thit-bam', 'hanh-la', false, 0),
  ('trung-chien-thit-bam', 'hanh-tay', false, 1),
  ('thit-bo-xao-hanh-tay', 'thit-bo', true, 0),
  ('thit-bo-xao-hanh-tay', 'hanh-tay', true, 1),
  ('thit-bo-xao-hanh-tay', 'ca-chua', false, 0),
  ('thit-bo-xao-hanh-tay', 'toi', false, 1),
  ('thit-bo-xao-hanh-tay', 'hanh-la', false, 2),
  ('suon-xao-chua-ngot', 'suon-non', true, 0),
  ('suon-xao-chua-ngot', 'ca-chua', true, 1),
  ('suon-xao-chua-ngot', 'khom', false, 0),
  ('suon-xao-chua-ngot', 'hanh-tay', false, 1),
  ('suon-xao-chua-ngot', 'toi', false, 2),
  ('dau-hu-sot-ca', 'dau-hu', true, 0),
  ('dau-hu-sot-ca', 'ca-chua', true, 1),
  ('dau-hu-sot-ca', 'hanh-la', false, 0),
  ('dau-hu-sot-ca', 'thit-bam', false, 1),
  ('ga-chien-nuoc-mam', 'dui-ga', true, 0),
  ('ga-chien-nuoc-mam', 'toi', false, 0),
  ('ga-chien-nuoc-mam', 'ot', false, 1),
  ('muc-xao-can', 'muc', true, 0),
  ('muc-xao-can', 'hanh-tay', false, 0),
  ('muc-xao-can', 'ca-rot', false, 1),
  ('muc-xao-can', 'toi', false, 2),
  ('banh-mi-trung-op-la', 'banh-mi', true, 0),
  ('banh-mi-trung-op-la', 'trung-ga', true, 1),
  ('banh-mi-trung-op-la', 'hanh-la', false, 0),
  ('banh-mi-trung-op-la', 'dua-chuot', false, 1),
  ('mi-goi-trung', 'mi-goi', true, 0),
  ('mi-goi-trung', 'trung-ga', true, 1),
  ('mi-goi-trung', 'cai-ngot', false, 0),
  ('mi-goi-trung', 'hanh-la', false, 1),
  ('mi-goi-trung', 'ca-chua', false, 2),
  ('chao-thit-bam', 'gao', true, 0),
  ('chao-thit-bam', 'thit-bam', true, 1),
  ('chao-thit-bam', 'hanh-la', false, 0),
  ('chao-thit-bam', 'gung', false, 1),
  ('chao-thit-bam', 'ca-rot', false, 2),
  ('com-rang-trung', 'gao', true, 0),
  ('com-rang-trung', 'trung-ga', true, 1),
  ('com-rang-trung', 'ca-rot', false, 0),
  ('com-rang-trung', 'hanh-la', false, 1),
  ('com-rang-trung', 'hanh-tay', false, 2),
  ('com-rang-trung', 'dau-que', false, 3),
  ('mien-xao-trung', 'mien', true, 0),
  ('mien-xao-trung', 'trung-ga', true, 1),
  ('mien-xao-trung', 'ca-rot', false, 0),
  ('mien-xao-trung', 'gia-do', false, 1),
  ('mien-xao-trung', 'hanh-la', false, 2),
  ('yen-mach-sua', 'yen-mach', true, 0),
  ('yen-mach-sua', 'sua-tuoi', true, 1),
  ('yen-mach-sua', 'lac', false, 0),
  ('ngu-coc-sua', 'ngu-coc', true, 0),
  ('ngu-coc-sua', 'sua-tuoi', true, 1),
  ('ngu-coc-sua', 'lac', false, 0),
  ('canh-chua-ca', 'ca-basa', true, 0),
  ('canh-chua-ca', 'ca-chua', true, 1),
  ('canh-chua-ca', 'me', false, 0),
  ('canh-chua-ca', 'khom', false, 1),
  ('canh-chua-ca', 'gia-do', false, 2),
  ('canh-chua-ca', 'rau-thom', false, 3),
  ('canh-rau-ngot-thit-bam', 'thit-bam', true, 0),
  ('canh-rau-ngot-thit-bam', 'mong-toi', true, 1),
  ('canh-rau-ngot-thit-bam', 'hanh-tim', false, 0),
  ('canh-rau-ngot-thit-bam', 'rau-den', false, 1),
  ('canh-bi-xanh-tom', 'bi-xanh', true, 0),
  ('canh-bi-xanh-tom', 'tom', true, 1),
  ('canh-bi-xanh-tom', 'hanh-la', false, 0),
  ('canh-ngheu-bau', 'ngheu', true, 0),
  ('canh-ngheu-bau', 'ca-chua', true, 1),
  ('canh-ngheu-bau', 'rau-thom', false, 0),
  ('canh-ngheu-bau', 'gung', false, 1),
  ('canh-trung-ca-chua', 'trung-ga', true, 0),
  ('canh-trung-ca-chua', 'ca-chua', true, 1),
  ('canh-trung-ca-chua', 'hanh-la', false, 0),
  ('canh-suon-bi-do', 'suon-non', true, 0),
  ('canh-suon-bi-do', 'bi-do', true, 1),
  ('canh-suon-bi-do', 'hanh-la', false, 0),
  ('canh-suon-bi-do', 'ca-rot', false, 1),
  ('rau-muong-xao-toi', 'rau-muong', true, 0),
  ('rau-muong-xao-toi', 'toi', false, 0),
  ('bap-cai-luoc', 'bap-cai', true, 0),
  ('bap-cai-luoc', 'trung-ga', false, 0),
  ('bap-cai-luoc', 'chanh', false, 1),
  ('su-su-xao-ca-rot', 'su-su', true, 0),
  ('su-su-xao-ca-rot', 'ca-rot', true, 1),
  ('su-su-xao-ca-rot', 'toi', false, 0),
  ('su-su-xao-ca-rot', 'thit-bam', false, 1),
  ('dau-que-xao-thit', 'dau-que', true, 0),
  ('dau-que-xao-thit', 'thit-bam', true, 1),
  ('dau-que-xao-thit', 'toi', false, 0),
  ('dau-que-xao-thit', 'hanh-tim', false, 1),
  ('cai-thao-xao-nam', 'cai-thao', true, 0),
  ('cai-thao-xao-nam', 'nam-rom', true, 1),
  ('cai-thao-xao-nam', 'toi', false, 0),
  ('cai-thao-xao-nam', 'ca-rot', false, 1);

commit;
